# Explorative and Predictive Analyses of Crime Data

# Step 1: Data Loading, Merging & Visualisation

## Importing the necessary modules

In [30]:
import os                            ## Operating system related task e.g. viewing and changing directoy
import sys                           ## Checking the current version of python etc 
import pandas as pd                  ## For data management
import numpy as np                   ## Array creation 

# For plotting charts 
%matplotlib inline
import matplotlib.pyplot as plt
import seaborn as sns

## Checking and Changing the Working Directory

In [31]:
#Checking
os.getcwd()

'C:\\Project_Analytics\\SA_Crime_Analysis'

In [32]:
#Changing
os.chdir(r'C:\Project_Analytics\SA_Crime_Analysis')

## Loading the Datasets

### Dataset A - Crime Reported and Police Station
This dataset is in csv (comma delimited) format

In [33]:
#Loading Dataset A
Dataset_A = pd.read_csv('dataset/Dataset_A.csv')

#Sorting the records using 'Police_Station'
Dataset_A.sort_values(['Police_Station'],ascending = [True], inplace=True)

#### Viewing the top 5 records

In [34]:
Dataset_A.head()

,Province,Police_Station,Crime_Category,Period_2015_2016
0,Eastern Cape,Aberdeen,All theft not mentioned elsewhere,51
25,Eastern Cape,Aberdeen,Theft out of or from motor vehicle,7
24,Eastern Cape,Aberdeen,Theft of motor vehicle and motorcycle,2
23,Eastern Cape,Aberdeen,Stock-theft,20
22,Eastern Cape,Aberdeen,Shoplifting,0

#### Viewing the properties of the Features | Variables | Coulms

In [35]:
Dataset_A.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 30861 entries, 0 to 5286
Data columns (total 4 columns):
Province            30861 non-null object
Police_Station      30861 non-null object
Crime_Category      30861 non-null object
Period_2015_2016    30861 non-null int64
dtypes: int64(1), object(3)
memory usage: 843.9+ KB

#### Reshaping the dataset from "long" to "wide" format

In [36]:
Dataset_A_Wide = Dataset_A.pivot_table(index=['Province','Police_Station'], columns='Crime_Category', values='Period_2015_2016')
Dataset_A_Wide.head(5)

Crime_Category               All theft not mentioned elsewhere  Arson  \
Province     Police_Station
Eastern Cape Aberdeen                                       51      4
             Addo                                           97      2
             Adelaide                                       47      2
             Afsondering                                    11      1
             Alexandria                                     76      0

Crime_Category               Assault with the intent to inflict grievous bodily harm  \
Province     Police_Station
Eastern Cape Aberdeen                                                       87
             Addo                                                          150
             Adelaide                                                       75
             Afsondering                                                    54
             Alexandria                                                     86

Crime_Category               Attempted murder  Bank robbery  \
Province     Police_Station
Eastern Cape Aberdeen                       5             0
             Addo                          25             0
             Adelaide                       0             0
             Afsondering                    5             0
             Alexandria                    17             0

Crime_Category               Burglary at non-residential premises  \
Province     Police_Station
Eastern Cape Aberdeen                                          15
             Addo                                              87
             Adelaide                                          22
             Afsondering                                        7
             Alexandria                                        27

Crime_Category               Burglary at residential premises  Carjacking  \
Province     Police_Station
Eastern Cape Aberdeen                                      74           0
             Addo                                         144           0
             Adelaide                                      85           0
             Afsondering                                   29           0
             Alexandria                                   116           2

Crime_Category               Commercial crime  Common assault  \
Province     Police_Station
Eastern Cape Aberdeen                       8              48
             Addo                           6              48
             Adelaide                      24              22
             Afsondering                    0              12
             Alexandria                    14              81

Crime_Category                    ...         Robbery at residential premises  \
Province     Police_Station       ...
Eastern Cape Aberdeen             ...                                       2
             Addo                 ...                                      12
             Adelaide             ...                                       2
             Afsondering          ...                                       6
             Alexandria           ...                                       6

Crime_Category               Robbery of cash in transit  \
Province     Police_Station
Eastern Cape Aberdeen                                 0
             Addo                                     1
             Adelaide                                 0
             Afsondering                              0
             Alexandria                               0

Crime_Category               Robbery with aggravating circumstances  \
Province     Police_Station
Eastern Cape Aberdeen                                             8
             Addo                                                41
             Adelaide                                            12
             Afsondering                                         13
             Alexandria                                          36

Crime_Category               Sexual Offences  \
Province     Police_Station
Eastern Cape Aberdeen                     14
             Addo                         55
             Adelaide                     18
             Afsondering                  28
             Alexandria                   41

Crime_Category               Sexual offences as result of police action  \
Province     Police_Station
Eastern Cape Aberdeen                                                 0
             Addo                                                     0
             Adelaide                                                 0
             Afsondering                                              0
             Alexandria                                               0

Crime_Category               Shoplifting  Stock-theft  \
Province     Police_Station
Eastern Cape Aberdeen                  0           20
             Addo                      0           21
             Adelaide                  7           22
             Afsondering               0           97
             Alexandria                5           35

Crime_Category               Theft of motor vehicle and motorcycle  \
Province     Police_Station
Eastern Cape Aberdeen                                            2
             Addo                                                8
             Adelaide                                            4
             Afsondering                                         0
             Alexandria                                          6

Crime_Category               Theft out of or from motor vehicle  \
Province     Police_Station
Eastern Cape Aberdeen                                         7
             Addo                                            11
             Adelaide                                        12
             Afsondering                                      6
             Alexandria                                      13

Crime_Category               Truck hijacking
Province     Police_Station
Eastern Cape Aberdeen                      0
             Addo                          0
             Adelaide                      0
             Afsondering                   0
             Alexandria                    3

[5 rows x 27 columns]

#### Flattening the pivoted dataset

In [37]:
Dataset_A_Wide_Flatten = pd.DataFrame(Dataset_A_Wide.to_records())
Dataset_A_Wide_Flatten.head()

,Province,Police_Station,All theft not mentioned elsewhere,Arson,Assault with the intent to inflict grievous bodily harm,Attempted murder,Bank robbery,Burglary at non-residential premises,Burglary at residential premises,Carjacking,...,Robbery at residential premises,Robbery of cash in transit,Robbery with aggravating circumstances,Sexual Offences,Sexual offences as result of police action,Shoplifting,Stock-theft,Theft of motor vehicle and motorcycle,Theft out of or from motor vehicle,Truck hijacking
0,Eastern Cape,Aberdeen,51,4,87,5,0,15,74,0,...,2,0,8,14,0,0,20,2,7,0
1,Eastern Cape,Addo,97,2,150,25,0,87,144,0,...,12,1,41,55,0,0,21,8,11,0
2,Eastern Cape,Adelaide,47,2,75,0,0,22,85,0,...,2,0,12,18,0,7,22,4,12,0
3,Eastern Cape,Afsondering,11,1,54,5,0,7,29,0,...,6,0,13,28,0,0,97,0,6,0
4,Eastern Cape,Alexandria,76,0,86,17,0,27,116,2,...,6,0,36,41,0,5,35,6,13,3

In [38]:
Dataset_A_Wide_Flatten.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1143 entries, 0 to 1142
Data columns (total 29 columns):
Province                                                   1143 non-null object
Police_Station                                             1143 non-null object
All theft not mentioned elsewhere                          1143 non-null int64
Arson                                                      1143 non-null int64
Assault with the intent to inflict grievous bodily harm    1143 non-null int64
Attempted murder                                           1143 non-null int64
Bank robbery                                               1143 non-null int64
Burglary at non-residential premises                       1143 non-null int64
Burglary at residential premises                           1143 non-null int64
Carjacking                                                 1143 non-null int64
Commercial crime                                           1143 non-null int64
Common assault                                             1143 non-null int64
Common robbery                                             1143 non-null int64
Driving under the influence of alcohol or drugs            1143 non-null int64
Drug-related crime                                         1143 non-null int64
Illegal possession of firearms and ammunition              1143 non-null int64
Malicious damage to property                               1143 non-null int64
Murder                                                     1143 non-null int64
Robbery at non-residential premises                        1143 non-null int64
Robbery at residential premises                            1143 non-null int64
Robbery of cash in transit                                 1143 non-null int64
Robbery with aggravating circumstances                     1143 non-null int64
Sexual Offences                                            1143 non-null int64
Sexual offences as result of police action                 1143 non-null int64
Shoplifting                                                1143 non-null int64
Stock-theft                                                1143 non-null int64
Theft of motor vehicle and motorcycle                      1143 non-null int64
Theft out of or from motor vehicle                         1143 non-null int64
Truck hijacking                                            1143 non-null int64
dtypes: int64(27), object(2)
memory usage: 250.1+ KB

### Check the datasets for duplicates
This is a major checklist before merging this dataset with the other datasets.

In [39]:
Dataset_A_Wide_Flatten[Dataset_A_Wide_Flatten.duplicated(['Police_Station'],keep=False)].head()
# There is no incident of duplicate records

Empty DataFrame
Columns: [Province, Police_Station, All theft not mentioned elsewhere, Arson, Assault with the intent to inflict grievous bodily harm, Attempted murder, Bank robbery, Burglary at non-residential premises, Burglary at residential premises, Carjacking, Commercial crime, Common assault, Common robbery, Driving under the influence of alcohol or drugs, Drug-related crime, Illegal possession of firearms and ammunition, Malicious damage to property, Murder, Robbery at non-residential premises, Robbery at residential premises, Robbery of cash in transit, Robbery with aggravating circumstances, Sexual Offences, Sexual offences as result of police action, Shoplifting, Stock-theft, Theft of motor vehicle and motorcycle, Theft out of or from motor vehicle, Truck hijacking]
Index: []

[0 rows x 29 columns]

#### Captitalising the names of police stations
This is done by adding "Police_Station_String" generated from "Police_Station"

In [40]:
Dataset_A_Wide_Flatten ["Police_Station_Normal"] = Dataset_A_Wide_Flatten['Police_Station']
Dataset_A_Wide_Flatten ["Police_Station"] = Dataset_A_Wide_Flatten['Police_Station'].str.upper()

In [41]:
Dataset_A_Wide_Flatten.head()

,Province,Police_Station,All theft not mentioned elsewhere,Arson,Assault with the intent to inflict grievous bodily harm,Attempted murder,Bank robbery,Burglary at non-residential premises,Burglary at residential premises,Carjacking,...,Robbery of cash in transit,Robbery with aggravating circumstances,Sexual Offences,Sexual offences as result of police action,Shoplifting,Stock-theft,Theft of motor vehicle and motorcycle,Theft out of or from motor vehicle,Truck hijacking,Police_Station_Normal
0,Eastern Cape,ABERDEEN,51,4,87,5,0,15,74,0,...,0,8,14,0,0,20,2,7,0,Aberdeen
1,Eastern Cape,ADDO,97,2,150,25,0,87,144,0,...,1,41,55,0,0,21,8,11,0,Addo
2,Eastern Cape,ADELAIDE,47,2,75,0,0,22,85,0,...,0,12,18,0,7,22,4,12,0,Adelaide
3,Eastern Cape,AFSONDERING,11,1,54,5,0,7,29,0,...,0,13,28,0,0,97,0,6,0,Afsondering
4,Eastern Cape,ALEXANDRIA,76,0,86,17,0,27,116,2,...,0,36,41,0,5,35,6,13,3,Alexandria

### Dataset B -  Police Station and the Population that they Cover 
This dataset is in xls (MS Excel) format

In [42]:
Dataset_B = pd.read_excel('dataset/Dataset_B.xlsx', sheetname = "Dataset_B")
Dataset_B.sort_values(['Police_Station'],ascending = [True], inplace=True)

In [43]:
Dataset_B.head()

  Police_Station  population_estimate
0       ABERDEEN          9866.916168
1      ACORNHOEK        127623.360239
2     ACTONVILLE         52830.848258
3           ADDO         20938.325245
4       ADELAIDE         13587.572554

In [44]:
Dataset_B.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1140 entries, 0 to 1139
Data columns (total 2 columns):
Police_Station         1140 non-null object
population_estimate    1140 non-null float64
dtypes: float64(1), object(1)
memory usage: 22.3+ KB

#### Check the datasets for duplicates

In [45]:
Dataset_B[Dataset_B.duplicated(['Police_Station'],keep=False)].head()
# There is no incident of duplicate records

Empty DataFrame
Columns: [Police_Station, population_estimate]
Index: []

### Dataset C -  Police Station and their Geo-Coordinates
This dataset is in tsv (tab delimited) format

In [46]:
Dataset_C = pd.read_csv('dataset/Dataset_C.tsv', sep='\t')
Dataset_C.sort_values(['Police_Station'],ascending = [True], inplace=True)

In [47]:
Dataset_C.head()

  Police_Station  LongitudeY  LatitudeX
0       ABERDEEN   -32.47634   24.06098
1      ACORNHOEK   -24.59710   31.04835
2     ACTONVILLE   -26.21198   28.29975
3           ADDO   -33.54769   25.69029
4       ADELAIDE   -32.70725   26.29255

#### Viewing the Attributes of the Variables

In [48]:
Dataset_C.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1142 entries, 0 to 1141
Data columns (total 3 columns):
Police_Station    1142 non-null object
LongitudeY        1142 non-null float64
LatitudeX         1142 non-null float64
dtypes: float64(2), object(1)
memory usage: 31.2+ KB

#### Check the datasets for duplicates

In [49]:
Dataset_C[Dataset_C.duplicated(['Police_Station'],keep=False)].head()
# There is no incident of duplicate records

Empty DataFrame
Columns: [Police_Station, LongitudeY, LatitudeX]
Index: []

### Merging Dataset A & B

In [50]:
print("Size of Dataset A =", len(Dataset_A_Wide_Flatten))
print("Size of Dataset B =", len(Dataset_B))
print("Size of Dataset C =", len(Dataset_C))

Size of Dataset A = 1143
Size of Dataset B = 1140
Size of Dataset C = 1142

#### Note:  Dataset A contains more records than Dataset B. Hence, Dataset A is the universal dataset.

In [51]:
#Left join
Dataset_A_and_B = pd.merge(Dataset_A_Wide_Flatten, Dataset_B, on='Police_Station', how='left')

In [52]:
Dataset_A_and_B.head(10)

,Province,Police_Station,All theft not mentioned elsewhere,Arson,Assault with the intent to inflict grievous bodily harm,Attempted murder,Bank robbery,Burglary at non-residential premises,Burglary at residential premises,Carjacking,...,Robbery with aggravating circumstances,Sexual Offences,Sexual offences as result of police action,Shoplifting,Stock-theft,Theft of motor vehicle and motorcycle,Theft out of or from motor vehicle,Truck hijacking,Police_Station_Normal,population_estimate
0,Eastern Cape,ABERDEEN,51,4,87,5,0,15,74,0,...,8,14,0,0,20,2,7,0,Aberdeen,9866.916168
1,Eastern Cape,ADDO,97,2,150,25,0,87,144,0,...,41,55,0,0,21,8,11,0,Addo,20938.325245
2,Eastern Cape,ADELAIDE,47,2,75,0,0,22,85,0,...,12,18,0,7,22,4,12,0,Adelaide,13587.572554
3,Eastern Cape,AFSONDERING,11,1,54,5,0,7,29,0,...,13,28,0,0,97,0,6,0,Afsondering,21314.682154
4,Eastern Cape,ALEXANDRIA,76,0,86,17,0,27,116,2,...,36,41,0,5,35,6,13,3,Alexandria,13844.567039
5,Eastern Cape,ALGOAPARK,505,4,137,14,0,259,259,24,...,325,53,1,223,2,89,429,1,Algoapark,35483.428245
6,Eastern Cape,ALICE,183,3,299,7,0,62,245,4,...,112,64,0,32,82,1,28,1,Alice,44033.995112
7,Eastern Cape,ALICEDALE,16,0,28,1,0,6,12,0,...,1,6,0,0,3,1,0,0,Alicedale,4420.374557
8,Eastern Cape,ALIWAL NORTH,205,1,140,0,0,69,141,1,...,33,25,0,74,47,15,71,0,Aliwal North,18525.527792
9,Eastern Cape,AVONDALE,12,3,87,4,0,0,46,0,...,15,26,0,0,43,1,1,0,Avondale,33902.072921

Note: In the code above: <br>
- The two datasets were merged using a feature that is common to the 2 of them i.e. <b> Police_Station </b> <br>
- Dataset_A is on the left
- Dataset_B is on the right
- Since I want all records on the left (universal). I specified: how='left'

In [53]:
Dataset_A_and_B.head()

,Province,Police_Station,All theft not mentioned elsewhere,Arson,Assault with the intent to inflict grievous bodily harm,Attempted murder,Bank robbery,Burglary at non-residential premises,Burglary at residential premises,Carjacking,...,Robbery with aggravating circumstances,Sexual Offences,Sexual offences as result of police action,Shoplifting,Stock-theft,Theft of motor vehicle and motorcycle,Theft out of or from motor vehicle,Truck hijacking,Police_Station_Normal,population_estimate
0,Eastern Cape,ABERDEEN,51,4,87,5,0,15,74,0,...,8,14,0,0,20,2,7,0,Aberdeen,9866.916168
1,Eastern Cape,ADDO,97,2,150,25,0,87,144,0,...,41,55,0,0,21,8,11,0,Addo,20938.325245
2,Eastern Cape,ADELAIDE,47,2,75,0,0,22,85,0,...,12,18,0,7,22,4,12,0,Adelaide,13587.572554
3,Eastern Cape,AFSONDERING,11,1,54,5,0,7,29,0,...,13,28,0,0,97,0,6,0,Afsondering,21314.682154
4,Eastern Cape,ALEXANDRIA,76,0,86,17,0,27,116,2,...,36,41,0,5,35,6,13,3,Alexandria,13844.567039

In [57]:
print("Size of Dataset B =", len(Dataset_A_and_B))
print("Size of Dataset C =", len(Dataset_C))

Size of Dataset B = 1143
Size of Dataset C = 1142

In [ ]:
#Left join
Dataset_A_B_C = pd.merge(Dataset_A_and_B, Dataset_B, on='Police_Station', how='left')